### ISSUE TITLE
Issue with running Convert_Json.py

### ISSUE THREAD

**Issue by jesmitty** [tiffsea/python-code#2]
I get the following error:
Traceback (most recent call last):
  File "C:\data\USPTO\convert-json.py", line 50, in <module>
    converter = Convert_Json(fn, title)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\data\USPTO\convert-json.py", line 10, in __init__
    self.mddata = self.format_json_to_md()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\data\USPTO\convert-json.py", line 25, in format_json_to_md
    for header, data in dct.items():
                        ^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

Is this a python version issue. I am running 3.12.1

**Comment by tiffsea** [comment]
Hi @jesmitty, thanks for your comment. Can you tell me the data type of the file passed in `fn` parameter for `Convert_Json()` init? It seems instead of passing a `json` type you may have passed another data type like `list`. Let me know how it goes.
